#!/usr/bin/env python3
"""Generate the detection catalog (docs/DETECTIONS.md) from the rules themselves.

Keeps human-readable documentation in lockstep with the rules: run it in CI (or a
pre-commit hook) and the catalog can never drift from what actually ships.

    python tools/generate_catalog.py detections/ --out docs/DETECTIONS.md
"""

from __future__ import annotations

import argparse
import sys
from collections import defaultdict
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from dac.loader import load_test_cases  # noqa: E402
from dac.matcher import load_rules  # noqa: E402

_TACTIC_ORDER = [
    "initial_access", "execution", "persistence", "privilege_escalation",
    "defense_evasion", "credential_access", "discovery", "lateral_movement",
    "collection", "command_and_control", "exfiltration", "impact",
]


def _first_sentence(text: str) -> str:
    clean = " ".join((text or "").split())
    for sep in (". ", "."):
        if sep in clean:
            return clean.split(sep)[0].strip() + "."
    return clean


def build_markdown(rules_dir: Path, cases_dir: Path) -> str:
    rules = load_rules(rules_dir)
    cases = {Path(c.rule).stem: c for c in load_test_cases(cases_dir)}

    by_tactic: dict[str, list] = defaultdict(list)
    for rule in rules:
        tactic = rule.attack_tactics[0] if rule.attack_tactics else "uncategorized"
        by_tactic[tactic].append(rule)

    total_tests = sum(c.total for c in cases.values())
    lines = [
        "# Detection Catalog",
        "",
        "> Generated by `tools/generate_catalog.py` — do not edit by hand.",
        "",
        f"**{len(rules)} detections** covering "
        f"**{len({t for r in rules for t in r.attack_techniques})} ATT&CK techniques**, "
        f"backed by **{total_tests} offline test assertions**.",
        "",
    ]

    ordered = [t for t in _TACTIC_ORDER if t in by_tactic]
    ordered += [t for t in by_tactic if t not in _TACTIC_ORDER]

    for tactic in ordered:
        lines.append(f"## {tactic.replace('_', ' ').title()}")
        lines.append("")
        lines.append("| Rule | ATT&CK | Severity | Tests | Summary |")
        lines.append("|------|--------|----------|-------|---------|")
        for rule in sorted(by_tactic[tactic], key=lambda r: r.title):
            case = cases.get(rule.path.stem)
            n = case.total if case else 0
            techs = ", ".join(rule.attack_techniques)
            summary = _first_sentence(rule.raw.get("description", ""))
            lines.append(
                f"| `{rule.path.stem}` | {techs} | {rule.level} | {n} | {summary} |"
            )
        lines.append("")

    return "\n".join(lines)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("rules_dir", nargs="?", default="detections", type=Path)
    parser.add_argument("--cases-dir", default="tests/cases", type=Path)
    parser.add_argument("--out", type=Path, default=Path("docs/DETECTIONS.md"))
    args = parser.parse_args(argv)

    md = build_markdown(args.rules_dir, args.cases_dir)
    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(md + "\n", encoding="utf-8")
    print(f"Wrote {args.out}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
